name: Build BlockLauncher

on:  
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: set JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: corretto
    - name: Build with CI build script
      run: tools/ci/ci_build.sh
      env:
        ASSETS_PASSWORD: ${{ secrets.ASSETS_PASSWORD }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_KEY_7Z_PASSWORD: ${{ secrets.SIGNING_KEY_7Z_PASSWORD }}

    - name: Upload build output
      uses: actions/upload-artifact@v3
      with:
        name: MCPELauncherApp
        path: MCPELauncherApp-release.apk
